---

- name: load ipmi modules at boot
  template:
    src: etc/modules-load.d/ipmi.conf.j2
    dest: '{{ ipmi_kernel_modules_conf }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: modules_conf_t
    selevel: s0
  register: ipmi_register_kernel_modules

- name: load ipmi modules
  service:
    name: '{{ ipmi_modules_load_service }}'
    state: restarted
  when: ipmi_register_kernel_modules.changed
  tags:
    - skip_ansible_lint

- name: ipmi ip source
  command: ipmitool lan set 2 ipsrc static
  when: ipmi_network is defined and
        ipmi_network.address is defined and
        ipmi_network.address

- name: ipmi ip address
  command: ipmitool lan set {{ ipmi_channel }} ipaddr {{ ipmi_network.address }}
  when: ipmi_network is defined and
        ipmi_network.address is defined and
        ipmi_network.address

- name: ipmi netmask
  command: ipmitool lan set {{ ipmi_channel }} netmask {{ ipmi_network.netmask }}
  when: ipmi_network is defined and
        ipmi_network.netmask is defined and
        ipmi_network.netmask

- name: ipmi gateway
  command: ipmitool lan set {{ ipmi_channel }} defgw ipaddr {{ ipmi_network.gateway }}
  when: ipmi_network is defined and
        ipmi_network.gateway is defined and
        ipmi_network.gateway

- name: ipmi snmp community
  command: ipmitool lan set {{ ipmi_channel }} snmp {{ ipmi_snmp_community }}
  when: ipmi_snmp_community is defined and ipmi_snmp_community
