---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::ipmi'
    - 'role::ipmi:install'
    - 'role::ipmi:config'

- import_tasks: kernelmod.yml
  tags:
    - 'role::ipmi'
    - 'role::ipmi:install'
    - 'role::ipmi:config'

- import_tasks: installation.yml
  when: ipmi_register_device.stat.exists | default(False)
  tags:
    - 'role::ipmi'
    - 'role::ipmi:install'

- import_tasks: configuration.yml
  when: ipmi_register_device.stat.exists | default(False)
  tags:
    - 'role::ipmi'
    - 'role::ipmi:config'
